{{ config(materialized='table')}}

with source as (
 select * from {{ ref('parsed_edi_data') }}
)

SELECT _FILE,
       _MODIFIED, 
       _LINE, 
       SEGMENT_TYPE,
       PARSED_COL_1 AS PACK,
       PARSED_COL_2 AS SIZE,
       PARSED_COL_3 AS PO4_UNIT_OR_BASIS_FOR_MEASUREMENT_CODE,
       PARSED_COL_4 AS PACKAGING_CODE,
       PARSED_COL_5 AS WEIGHT_QUALIFIER,
       PARSED_COL_6 AS GROSS_WEIGHT_PER_PACK,
       PARSED_COL_7 AS PO4_02_UNIT_OR_BASIS_FOR_MEASUREMENT_CODE,
       PARSED_COL_8 AS GROSS_VOLUME_PER_PACK,
       PARSED_COL_9 AS PO4_03_UNIT_OR_BASIS_FOR_MEASUREMENT_CODE,
       PARSED_COL_10 AS PO4_LENGTH,
       PARSED_COL_11 AS PO4_WIDTH,
       PARSED_COL_12 AS PO4_HEIGHT,
       PARSED_COL_13 AS PO4_04_UNIT_OR_BASIS_FOR_MEASUREMENT_CODE,
       PARSED_COL_14 AS INNER_PACK,
       PARSED_COL_15 AS PO4_SURFACE_LAYER_POSITION_CODE,
       PARSED_COL_16 AS ASSIGNED_IDENTIFICATION_01,
       PARSED_COL_17 AS ASSIGNED_IDENTIFICATION_02,
       PARSED_COL_18 AS PO4_NUMBER FROM source WHERE SEGMENT_TYPE = 'PO4'
