{{ config(materialized='table')}}

with source as (
 select * from {{ ref('parsed_edi_data') }}
)

SELECT _FILE,
       _MODIFIED, 
       _LINE, 
       SEGMENT_TYPE,
       PARSED_COL_1 AS FUNCTIONAL_IDENTIFIER_CODE,
       PARSED_COL_2 AS APPLICATION_SENDERS_CODE,
       PARSED_COL_3 AS APPLICATION_RECEIVERS_CODE,
       PARSED_COL_4 AS GS_DATE,
       PARSED_COL_5 AS GS_TIME,
       PARSED_COL_6 AS GS_GROUP_CONTROL_NUMBER,
       PARSED_COL_7 AS RESPONSIBLE_AGENCY_CODE,
       PARSED_COL_8 AS VERSION_RELEASE_INDUSTRY_IDENTIFIER FROM source WHERE SEGMENT_TYPE = 'GS'
