{{ config(materialized='table')}}

with source as (
 select * from {{ ref('parsed_edi_data') }}
)

SELECT _FILE,
       _MODIFIED, 
       _LINE, 
       SEGMENT_TYPE,
       PARSED_COL_1 AS AUTHORIZATION_INFORMATION_QUALIFIER,
       PARSED_COL_2 AS AUTHORIZATION_INFORMATION,
       PARSED_COL_3 AS SECURITY_INFORMATION_QUALIFIER,
       PARSED_COL_4 AS SECURITY_INFORMATION,
       PARSED_COL_5 AS INTERCHANGE_ID_QUALIFIER_1,
       PARSED_COL_6 AS INTERCHANGE_SENDER_ID,
       PARSED_COL_7 AS INTERCHANGE_ID_QUALIFIER_2,
       PARSED_COL_8 AS INTERCHANGE_RECEIVER_ID,
       PARSED_COL_9 AS INTERCHANGE_DATE,
       PARSED_COL_10 AS INTERCHANGE_TIME,
       PARSED_COL_11 AS REPETIION_SEPARATOR,
       PARSED_COL_12 AS INTERCHANGE_CONTROL_VERSION_NUMBER_CODE,
       PARSED_COL_13 AS INTERCHANGE_CONTROL_NUMBER,
       PARSED_COL_14 AS ACKNOWLEDGEMENT_REQUESTED_CODE,
       PARSED_COL_15 AS INTECHANGE_USAGE_INDICATOR_CODE,
       PARSED_COL_16 AS COMPONENT_ELEMENT_SEPARATOR FROM source WHERE SEGMENT_TYPE = 'ISA'
