{{ config(materialized='table')}}

with source as (
 select * from {{ ref('parsed_edi_data') }}
)

SELECT _FILE,
       _MODIFIED, 
       _LINE, 
       SEGMENT_TYPE,
       PARSED_COL_1 AS TERMS_TYPE_CODE,
       PARSED_COL_2 AS TERMS_BASIS_DATE_CODE,
       PARSED_COL_3 AS TERMS_DISCOUNT_PERCENT,
       PARSED_COL_4 AS TERMS_DISCOUNT_DUE_DATE,
       PARSED_COL_5 AS TERMS_DISCOUNT_DAYS_DUE,
       PARSED_COL_6 AS TERMS_NET_DUE_DATE,
       PARSED_COL_7 AS TERMS_NET_DAYS,
       PARSED_COL_8 AS TERMS_DISCOUNT_AMOUNT,
       PARSED_COL_9 AS TERMS_DEFERRED_DUE_DATE,
       PARSED_COL_10 AS DEFERRED_AMOUNT_DUE,
       PARSED_COL_11 AS PERCENT_OF_INVOICE_PAYABLE,
       PARSED_COL_12 AS ITD_DESCRIPTION,
       PARSED_COL_13 AS DAY_OF_MONTH,
       PARSED_COL_14 AS PAYMENT_METHOD_TYPE_CODE,
       PARSED_COL_15 AS PERCENTAGE_AS_DECIMAL FROM source WHERE SEGMENT_TYPE = 'ITD'
