{{ config(materialized='table')}}

with source as (
 select * from {{ ref('parsed_edi_data') }}
)

SELECT _FILE,
       _MODIFIED, 
       _LINE, 
       SEGMENT_TYPE,
       PARSED_COL_1 AS ENTITY_IDENTIFIER_CODE,
       PARSED_COL_2 AS N1_NAME,
       PARSED_COL_3 AS N1_IDENTIFIER_CODE_QUALIFIER,
       PARSED_COL_4 AS N1_IDENTIFICATION_CODE,
       PARSED_COL_5 AS ENTITY_RELATIONSHIP_CODE,
       PARSED_COL_6 AS N1_ENTITY_IDENTIFIER_CODE FROM source WHERE SEGMENT_TYPE = 'N1'
